name: ml_nlp
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9.12
  - tensorflow=2.4.1
  - nltk=3.7
  - numpy=1.22.3
  - spacy=3.3.0
  - scikit-learn=1.0.2
  - textblob=0.15.3
  - jupyter=1.0.0
  - ipywidgets=7.6.5
  - matplotlib=3.5.1
  - gensim=4.1.2
  - pandas=1.4.2
  - keras=2.9.0

